# Generated by Django 2.0.7 on 2018-07-26 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20180726_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['votes', '-created']},
        ),
    ]
