# Generated by Django 2.0.7 on 2018-07-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_link_video_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='embed_url',
            field=models.URLField(default='https://www.youtube.com/embed/9g2U12SsRns', verbose_name='embed url'),
            preserve_default=False,
        ),
    ]
