# Generated by Django 2.0.7 on 2018-07-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_link_embed_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-votes', '-created']},
        ),
    ]
